### ISSUE TITLE
how to install IUP ?

### ISSUE THREAD

**Issue by ASHIT-AXAR** [carblue/iup#1]
hello
would you please help me to get started with IUP ? im confused in how to install IUP ( C language ).
i don't need to compile IUP myself, just fast start with precompiled binaries in windows 7
where should i download binaries ? i have downloaded IUP zip file (~12MB) from sourceforge website ( also IM and DC ), there are "src" and "include" folders but no "lib" folder, do i need IUP ".lib" files to build a helloworld example ?
it's couple of months i started D, but no luck in finding an easy to use gui library.
any help is appreciated, thanks.

**Comment by carblue** [comment]
hi,
probably some of the precompiled binaries for windows are all You need; YES, You need .lib files and if You go the recommended dynamic way also the .dll files!
as an example for IUP, go to
https://sourceforge.net/projects/iup/files/3.27/Windows%20Libraries/Dynamic/
and pick a .zip that matches Your Visual Studio edition (dmd-win uses the VS linker; that page explains the relationship).
I checked e.g. "iup-3.27_Win64_dll14_lib.zip": It has import libraries .lib and .dll included.
Put all the import libraries .lib and shared binaries .dll from IUP/CD/IM 64 bit Windows "Libraries/Dynamic" downloads to the folder lib/windows-x86_64 (inside Your clone of my iup D package. Also the .dll s should be copied to some location on Your machine where Windows looks for DLL (some location within PATH), thus then Your D executable using IUP/CD/IM will also work from other locations than just the build location and that's required also for this:
I recommend to check Your installation by also downloading https://sourceforge.net/projects/iup/files/3.27/Tools%20Executables/iup-3.27_Win64_bin.zip/download
and run iuptest.exe if that works.
I personally gave up using Qt or wxWidgets in favour of IUP, that better fits my needs and is much faster to learn.
The tricky part with IUP is, that You may need more .lib than defined in my dub.json (it depends on the IUP controls and possibly CD/IM functions that Your code uses; the linker will complain then). It's explained somewhere in the IUP/CD/IM documentation of PUC. In that case look into toberenameddub.json which .lib s are defined there within "sourceFiles-windows-x86_64" as the extreme case. Don't rely on my D package code e.g. "pragma(lib, "iupim.lib");" to pull in those .lib when dub separates compiling and linking. Years ago I lost interest in these nasty Windows subtleties, but IIRC dub nowadays has a switch to not separate compiling and linking.

Let me know if that worked for You
Cheers

**Comment by ASHIT-AXAR** [comment]
thank you, i installed environment and can run examples correctly (for C language)
now i should setup DMD then start with your libraries. it might take a while. i will notify if anything goes wrong.
thank you for your help.
