### ISSUE TITLE
How to enable visual styles ?

### ISSUE THREAD

**Issue by ASHIT-AXAR** [carblue/iup#2]
hello @carblue 
how do you enable visual styles ?
i build the "examples\tutorial\example2_1.d". have no visual styles. any suggestion on how to do that?
i could find how to detach console with a simple search but no luck on visual style.
in gcc simply passing the "X.res" file to linker enables both the visual style and app icon but in dmd the same "X.res" file not working.

**Comment by carblue** [comment]
I don't know (nor usually use Windows, not to mention Windows Visual Styles).
Bear in mind, this is a binding. You may find answers in the IUP docs, from it's maintainer, and/or maybe it's related to how compiler/linker (DMD etc.) deals with that.
Also, there are many bindings to IUP for several programming languages, some of which mention Windows Visual Styles.
If the solution ends up in using a resource file .rc, then simply add that (or the output of a resource compiler ?) to DMD's source files to be compiled, e.g. via dub.json, from:
https://forum.dlang.org/thread/bn93bp$19kg$1@digitaldaemon.com
https://wiki.dlang.org/Using_Windows_Resource_Files_with_D2

Some Google search results mentioning IUP Windows Visual Style
https://webserver2.tecgraf.puc-rio.br/iup/en/guide.html
https://webserver2.tecgraf.puc-rio.br/iup/en/drv/win32.html
https://sourceforge.net/p/iup/mailman/iup-users/?viewmonth=201811
The IUP source package contains sample manifests for win32 and win64, see also iup.rc. folder /etc
https://github.com/KISS-UI/kiss-ui  (seems to refer to win32 only)

When You found the solution, it might be helpful for other users to publish that in this issue.
