### ISSUE TITLE
How to build iup for non-x86 architectures

### ISSUE THREAD

**Issue by lenoil98** [carblue/iup#3]
I want to use iup for d on FreeBSD/powerpc.  I have built iup libraries, from the original source for the target architecture. Do I need to build binaries from your code, or do I only need the wrapper?

Any recommendations are appreciated.

**Comment by carblue** [comment]
Hi,
For the D binding You don't need a special build step apart from Your application, that will use the IUP libraries.
I would recommend using dub build manager, using my binding as dependancy:
Look at https://dub.pm/dub-reference/build_settings/
with respect that "my, binding's" dub.json states:
"targetType": "sourceLibrary",

"sourceLibrary" 	This target type does not generate a binary, but rather forces dub to add all source files directly to the same compiler invocation as the dependent project. For details, see [Build Hooks](https://dub.pm/dub-reference/hooks/#targettype-sourcelibrary)


An example invocation might clarify a lot.
You have my binding package downloaded? Goto folder iup/examples/C and check, that file tree.d has access rights to be executed, also make sure You have compiler tool rdmd. Then see the first line of tree.d, where it refers to file cmdfile_plusD for details of where to find the tobe-imported iup-binding files and which IUP/CD libraries to link. Invoke in directory .......iup/examples/C, i.e. call the source file tree.d like a scrpt-execution:
./tree.d

If all went well a window opens, created by IUP, titled `IupTree`

**Comment by lenoil98** [comment]
Thanks! Go everything working. Cheers!
